language: elixir

elixir:
  - 1.9
  - 1.10

otp_release:
  - 20.0
  - 21.0
  - 22.0

jobs:
  exclude:
  - elixir: 1.10
    opt_release: 20.0

services:
  - postgresql

before_script:
  - psql -U postgres -c "CREATE USER $ELIXIR_DB_USER WITH CREATEDB LOGIN ENCRYPTED PASSWORD '$DB_PW'"

script:
  - mkdir tmp
  - mix compile --force --warning-as-errors
  - mix format --check-formatted
  - mix credo --strict
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
  - mix test --trace
