version: "3.5"

services:
  database:
    image: postgres:alpine
    container_name: database
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    networks:
      - database_net

  app:
    build: .
    container_name: elixir_app
    environment:
      MIX_ENV: $APP_ENV
      ELIXIR_DB_USER:
      DB_PW:
      DATABASE_URL: "database"
      POOL_SIZE: 10
      APP_SECRET:
      HOST_IP: "database"
    ports:
      - "4000:4000"
    networks:
      - database_net

networks:
  database_net:
    driver: bridge
