FROM elixir:1.10

ARG DB_USER
ARG DB_PW

RUN apt-get update -y \
  && apt-get install -y postgresql postgresql-contrib \
  && pg_ctlcluster 11 main start \
  && sleep 6 \
  && psql -c "CREATE USER $DB_USER WITH CREATEDB LOGIN ENCRYPTED PASSWORD '$DB_PW'"

RUN adduser -D -g "" wjmill

USER wjmill

COPY . /home/wjmill/app

WORKDIR /home/wjmill/app

ENTRYPOINT sh mix test
