FROM elixir:1.10

RUN apt-get update -y \
    && apt-get install -y postgresql postgresql-contrib

USER postgres

RUN pg_ctlcluster 11 main start \
    && sleep 8 \
    && psql -U postgres -c "CREATE USER elixirapps WITH CREATEDB LOGIN ENCRYPTED PASSWORD 'widner'"

USER root

RUN useradd -d /home/wjmill -g 1000 wjmill

USER wjmill

COPY . /home/wjmill/app

WORKDIR /home/wjmill/app

ENTRYPOINT sh mix test
